name: Auto Minify Site Files

# الـ triggers
on:
  push:
    branches:
      - main           # غيّرها إذا موقعك يُنشر من فرع آخر مثل gh-pages
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
  workflow_dispatch:   # يتيح التشغيل اليدوي لأي وقت من صفحة Actions

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Minify HTML, CSS, JS (تجاهل الصور والخطوط والمجلدات الأخرى)
      - name: Minify HTML, CSS, and JS
        id: minify
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'               # جميع الملفات في الجذر
          exclude: 'images,fonts' # تجاهل هذه المجلدات

      # 3️⃣ Commit & Push التغييرات الناتجة عن Minify
      - name: Commit and push minified files
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-minified files" || echo "No changes to commit"
          git push

      # 4️⃣ إشعار النجاح
      - name: Report result
        if: ${{ success() }}
        run: echo "✅ Auto-minify completed successfully!"

      # 5️⃣ إشعار الفشل
      - name: Report failure
        if: ${{ failure() }}
        run: echo "❌ Auto-minify failed! Please check previous steps."
