name: Auto Minify Site Files (with Babel)

on:
  push:
    branches:
      - main        # غيّرها إذا موقعك يُنشر من فرع آخر مثل gh-pages
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
  workflow_dispatch: # يتيح التشغيل اليدوي من صفحة Actions

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ تحميل المستودع
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ تثبيت أدوات التصغير
      - name: Install Babel and minifiers
        run: |
          npm install -g babel-cli babel-preset-minify clean-css-cli html-minifier-terser

      # 3️⃣ تصغير HTML
      - name: Minify HTML files
        run: |
          find . -type f -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {} {} \;

      # 4️⃣ تصغير CSS
      - name: Minify CSS files
        run: |
          find . -type f -name "*.css" -exec cleancss -O2 -o {} {} \;

      # 5️⃣ تصغير JavaScript (بما في ذلك ملفات import/export)
      - name: Minify JavaScript with Babel (ES Modules supported)
        run: |
          find . -type f -name "*.js" -exec npx babel {} --out-file {} --presets=minify \;

      # 6️⃣ حفظ التعديلات في المستودع
      - name: Commit and push minified files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-minified HTML, CSS, and JS files" || echo "No changes to commit"
          git push

      # 7️⃣ إشعار النجاح أو الفشل
      - name: Report success
        if: ${{ success() }}
        run: echo "✅ All files minified successfully!"

      - name: Report failure
        if: ${{ failure() }}
        run: echo "❌ Auto-minify failed! Please check previous steps."
